version: '3.8'

services:
  app:
    build: .
    image: petrovskyy/lr2
    container_name: app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - mynetwork

  mysql:
    image: mysql
    container_name: app-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - mynetwork

volumes:
  mysql-data:
    name: app-mysql-data

networks:
  mynetwork:
    name: my-network-bridge
    driver: bridge
