# Generated by Django 5.0.4 on 2024-05-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_employee_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Cashier',
        ),
    ]
