# Generated by Django 5.0.4 on 2024-05-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
