# Generated by Django 5.0.4 on 2024-05-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
