# Generated by Django 5.0.4 on 2024-05-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_rename_discount_fraction_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='clients_used',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
