# Generated by Django 5.0.4 on 2024-05-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_employee_cashier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cashier',
            new_name='Employee',
        ),
    ]
