# Generated by Django 5.0.4 on 2024-05-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_cashier_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seller',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.employee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
