# Generated by Django 5.0.4 on 2024-05-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_username',
            new_name='user',
        ),
    ]
