# Generated by Django 5.0.4 on 2024-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_rename_user_username_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='employee_photos/'),
        ),
    ]
