# Generated by Django 5.0.4 on 2024-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='employee_photos/'),
        ),
    ]
