# Generated by Django 5.0.4 on 2024-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_employee_photo_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Cashier', max_length=100),
        ),
    ]
