# Generated by Django 5.0.4 on 2024-05-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_coupon_ticket_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_fraction',
            new_name='discount',
        ),
    ]
