# Generated by Django 5.0.4 on 2024-05-23 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_coupon_clients_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
