# Generated by Django 5.1 on 2024-08-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_position_remove_employee_position_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.position'),
        ),
    ]
