# Generated by Django 5.1 on 2024-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_companyinformation_delete_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInformation',
        ),
    ]
