# Generated by Django 5.1 on 2024-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_delete_companyinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('information', models.CharField(max_length=10000)),
                ('history', models.CharField(max_length=10000)),
                ('video', models.FileField(upload_to='videos/')),
                ('certificate_ru_head', models.ImageField(upload_to='certificates/')),
                ('certificate_ru_tail', models.ImageField(upload_to='certificates/')),
                ('certificate_en_head', models.ImageField(upload_to='certificates/')),
                ('certificate_en_tail', models.ImageField(upload_to='certificates/')),
                ('details', models.CharField(max_length=10000)),
            ],
        ),
    ]
