# Generated by Django 5.1 on 2024-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_companyinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='logo',
            field=models.ImageField(upload_to='company_logo/'),
        ),
    ]
