# Generated by Django 5.1 on 2024-09-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_alter_companyinformation_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInformation',
            new_name='CompanyInfo',
        ),
    ]
