# Generated by Django 5.1 on 2024-09-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_cart_cartitem_cart_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
