# Generated by Django 5.1 on 2024-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_en_head',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_en_tail',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_ru_head',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_ru_tail',
            field=models.CharField(max_length=10000),
        ),
    ]
