# Generated by Django 5.1 on 2024-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_alter_companyinfo_certificate_en_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='completion',
            field=models.DateField(null=True),
        ),
    ]
