# Generated by Django 5.1 on 2024-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_coupon_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
