version: '3.8'

services:
  app:
    build: ./client
    container_name: app
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mynetwork

  api-server:
    build: ./server
    container_name: api-server
    restart: always
    ports:
      - 5001:5001
    networks:
      - mynetwork
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:
    name: app-mongo-data
    driver: local

networks:
  mynetwork:
    driver: bridge
